language: ruby
sudo: false
rvm:
  - 2.2.2
  - 2.3.0
  - jruby-9.0.5.0
  - rbx
services: redis
before_script:
  - cd test/dummy && RAILS_ENV=test bundle exec rake db:migrate && cd -
matrix:
  allow_failures:
    - rvm: rbx
